In [1]:
import numpy as np
import pandas as pd

min_common_items = 4
min_eval_users = 3

pd.options.display.max_rows = 999 
pd.options.display.max_columns = 999

In [2]:
df_ratings = pd.read_csv('ratings.csv', sep=',', skiprows=0, header=0)

print(df_ratings.shape)
display(df_ratings.info())
display(df_ratings.head())

(100836, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

None

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
df_movies = pd.read_csv('movies.csv', sep=',', skiprows=0, header=0)

print(df_movies.shape)
display(df_movies.info())
display(df_movies.head())

(9742, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

None

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
df_merge = pd.merge(df_ratings, df_movies, on="movieId", how='inner')
df_merge.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [5]:
df = df_merge.pivot_table(index='userId', columns='title', values='rating').reset_index(drop=True)
print(df.shape)
display(df.head())

(610, 9719)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...All the Marbles (1981),...And Justice for All (1979),00 Schneider - Jagd auf Nihil Baxter (1994),1-900 (06) (1994),10 (1979),10 Cent Pistol (2015),10 Cloverfield Lane (2016),10 Items or Less (2006),10 Things I Hate About You (1999),10 Years (2011),"10,000 BC (2008)",100 Girls (2000),100 Streets (2016),101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),101 Dalmatians II: Patch's London Adventure (2003),101 Reykjavik (101 Reykjavík) (2000),102 Dalmatians (2000),10th & Wolf (2006),"10th Kingdom, The (2000)","10th Victim, The (La decima vittima) (1965)","11'09""01 - September 11 (2002)",11:14 (2003),"11th Hour, The (2007)",12 Angry Men (1957),12 Angry Men (1997),12 Chairs (1971),12 Chairs (1976),12 Rounds (2009),12 Years a Slave (2013),127 Hours (2010),13 Assassins (Jûsan-nin no shikaku) (2010),13 Ghosts (1960),13 Going on 30 (2004),13 Hours (2016),13 Sins (2014),13 Tzameti (2005),13th (2016),"13th Warrior, The (1999)",1408 (2007),1492: Conquest of Paradise (1992),15 Minutes (2001),16 Blocks (2006),17 Again (2009),1776 (1972),18 Again! (1988),187 (One Eight Seven) (1997),1900 (Novecento) (1976),1941 (1979),1969 (1988),1984 (Nineteen Eighty-Four) (1984),2 Days in New York (2012),2 Days in Paris (2007),2 Days in the Valley (1996),"2 Fast 2 Furious (Fast and the Furious 2, The) (2003)",2 Guns (2013),20 Dates (1998),20 Feet from Stardom (Twenty Feet from Stardom) (2013),20 Million Miles to Earth (1957),"20,000 Days on Earth (2014)","20,000 Leagues Under the Sea (1916)","20,000 Leagues Under the Sea (1954)",200 Cigarettes (1999),2001 Maniacs (2005),2001: A Space Odyssey (1968),2010: The Year We Make Contact (1984),2012 (2009),2046 (2004),2048: Nowhere to Run (2017),21 (2008),21 Grams (2003),21 Jump Street (2012),21 Up (1977),21 and Over (2013),22 Jump Street (2014),24 Hour Party People (2002),25th Hour (2002),27 Dresses (2008),28 Days (2000),28 Days Later (2002),28 Up (1985),28 Weeks Later (2007),3 Days to Kill (2014),3 Extremes (Three... Extremes) (Saam gaang yi) (2004),3 Idiots (2009),3 Ninjas (1992),3 Ninjas Kick Back (1994),3 Ninjas Knuckle Up (1995),3 Ninjas: High Noon On Mega Mountain (1998),3 Women (Three Women) (1977),3 dev adam (Three Giant Men) (1973),3-Iron (Bin-jip) (2004),30 Days of Night (2007),30 Minutes or Less (2011),300 (2007),3000 Miles to Graceland (2001),300: Rise of an Empire (2014),31 (2016),35 Up (1991),"39 Steps, The (1935)",3:10 to Yuma (1957),3:10 to Yuma (2007),4 Little Girls (1997),"4 Months, 3 Weeks and 2 Days (4 luni, 3 saptamâni si 2 zile) (2007)",40 Days and 40 Nights (2002),"40-Year-Old Virgin, The (2005)","400 Blows, The (Les quatre cents coups) (1959)",42 (2013),42 Up (1998),42nd Street (1933),47 Ronin (2013),48 Hrs. (1982),49 Up (2005),5 Centimeters per Second (Byôsoku 5 senchimêtoru) (2007),5 to 7 (2014),"5,000 Fingers of Dr. T, The (1953)",50 First Dates (2004),50/50 (2011),52 Pick-Up (1986),54 (1998),6 Days to Air: The Making of South Park (2011),61* (2001),"6th Day, The (2000)","6th Man, The (Sixth Man, The) (1997)",7 Days in Hell (2015),7 Faces of Dr. Lao (1964),"7th Voyage of Sinbad, The (1958)",8 1/2 (8½) (1963),8 Heads in a Duffel Bag (1997),8 Mile (2002),8 Seconds (1994),8 Women (2002),8 ½ Women (a.k.a. 8 1/2 Women) (a.k.a. Eight and a Half Women) (1999),800 Bullets (800 Balas) (2002),84 Charing Cross Road (1987),8MM (1999),9 (2009),9 1/2 Weeks (Nine 1/2 Weeks) (1986),9/11 (2002),96 Minutes (2011),964 Pinocchio (1991),99 francs (2007),9to5: Days in Porn (a.k.a. 9 to 5: Days in Porn) (2008),A Bad Moms Christmas (2017),A Christmas Story Live! (2017),A Cosmic Christmas (1977),A Detective Story (2003),A Dog's Purpose (2017),A Flintstones Christmas Carol (1994),A German Life (2016),A Home at the End of the World (2004),A Man Called Blade (1977),A Man from Boulevard des Capucines (1987),A Merry Friggin' Christmas (2014),A Midsummer Night's Dream (2016),A Million Ways to Die in the West (2014),A Most Wanted Man (2014),A Perfect Day (2015),A Pigeon Sat on a Branch Reflecting on Existence (2014),A Plasticine Crow (1981),A Quiet Place (2018),A Silent Voice (2016),A Story of Children and Film (2013),A Street Cat Named Bob (2016),A Very Murray Christmas (2015),A Walk in the Woods (2015),A Wrinkle in Time (2018),"A-Team, The (2010)",A.I. Artificial Intelligence (2001),"ABCs of Death, The (2012)",ARQ (2016),AVP: Alien vs. Predator (2004),AVPR: Aliens vs. Predator - Requiem (2007),"Abandoned, The (2006)",Abbott and Costello Meet Frankenstein (1948),Abduction (2011),"Abominable Dr. Phibes, The (1971)","Abominable Snowman, The (Abominable Snowman of the Himalayas, The) (1957)",About Adam (2000),About Last Night (2014),About Last Night... (1986),About Schmidt (2002),About Time (2013),About a Boy (2002),Above the Law (1988),Above the Rim (1994),Abraham Lincoln: Vampire Hunter (2012),Absence of Malice (1981),"Absent-Minded Professor, The (1961)",Absentia (2011),Absolute Power (1997),Absolutely Anything (2015),"Abyss, The (1989)",Accepted (2006),"Accidental Spy, The (Dak miu mai shing) (2001)","Accidental Tourist, The (1988)","Accused, The (1988)",Ace Ventura: Pet Detective (1994),Ace Ventura: When Nature Calls (1995),"Ace in the Hole (Big Carnival, The) (1951)",Aces: Iron Eagle III (1992),"Acid House, The (1998)",Across the Hall (2009),Across the Universe (2007),"Act of Killing, The (2012)",Act of Valor (2012),Action Jackson (1988),Adam and Eve (National Lampoon's Adam & Eve) (2005),Adam's Apples (Adams æbler) (2005),Adam's Rib (1949),Adanggaman (2000),Adaptation (2002),Addams Family Reunion (1998),Addams Family Values (1993),"Addams Family, The (1991)",Addicted to Love (1997),"Addiction, The (1995)","Adjustment Bureau, The (2011)",Admission (2013),Adventureland (2009),Adventures Of Sherlock Holmes And Dr. Watson: The Twentieth Century Approaches (1986),Adventures in Babysitting (1987),Adventures in Plymptoons! (2011),"Adventures of Baron Munchausen, The (1988)","Adventures of Buckaroo Banzai Across the 8th Dimension, The (1984)","Adventures of Elmo in Grouchland, The (1999)","Adventures of Ford Fairlane, The (1990)","Adventures of Huck Finn, The (1993)","Adventures of Ichabod and Mr. Toad, The (1949)","Adventures of Mary-Kate and Ashley, The: The Case of the Christmas Caper (1995)","Adventures of Milo and Otis, The (Koneko monogatari) (1986)",Adventures of Mowgli: The Kidnapping (1968),"Adventures of Pinocchio, The (1996)","Adventures of Pluto Nash, The (2002)","Adventures of Priscilla, Queen of the Desert, The (1994)","Adventures of Robin Hood, The (1938)","Adventures of Rocky and Bullwinkle, The (2000)","Adventures of Sebastian Cole, The (1998)","Adventures of Sharkboy and Lavagirl 3-D, The (2005)","Adventures of Tintin, The (2011)",Advise and Consent (1962),Aelita: The Queen of Mars (Aelita) (1924),Aeon Flux (2005),"Affair of Love, An (Liaison pornographique, Une) (1999)","Affair of the Necklace, The (2001)","Affair to Remember, An (1957)",Afflicted (2013),Affliction (1997),Afonya (1975),Africa: The Serengeti (1994),African Cats (2011),"African Queen, The (1951)",Afro Samurai (2007),Afro Samurai: Resurrection (2009),After Earth (2013),After Hours (1985),After Life (Wandafuru raifu) (1998),After the Fox (Caccia alla volpe) (1966),After the Sunset (2004),After the Thin Man (1936),After the Wedding (Efter brylluppet) (2006),Afterglow (1997),Against All Odds (1984),Against the Ropes (2004),"Age of Innocence, The (1993)",Agent Cody Banks (2003),Agent Cody Banks 2: Destination London (2004),Agnes of God (1985),"Agony and the Ecstasy, The (1965)",Agora (2009),"Aguirre: The Wrath of God (Aguirre, der Zorn Gottes) (1972)",Aileen: Life and Death of a Serial Killer (2003),Air America (1990),Air Bud (1997),Air Bud: Golden Receiver (1998),Air Force One (1997),"Air I Breathe, The (2007)","Air Up There, The (1994)",Airborne (1993),Airheads (1994),Airplane II: The Sequel (1982),Airplane! (1980),Airport '77 (1977),Airport (1970),Airport 1975 (1974),Akeelah and the Bee (2006),Akira (1988),Akira Kurosawa's Dreams (Dreams) (1990),Aladdin (1992),Aladdin and the King of Thieves (1996),"Alamo, The (1960)",Alan Partridge: Alpha Papa (2013),Alaska (1996),Alaska: Spirit of the Wild (1997),Albatross (2011),Albino Alligator (1996),Alesha Popovich and Tugarin the Dragon (2004),Alex Cross (2012),Alex and Emma (2003),Alexander (2004),Alexander Nevsky (Aleksandr Nevskiy) (1938),Alfie (1966),Alfie (2004),Ali (2001),Ali G Indahouse (2002),Ali Wong: Baby Cobra (2016),Ali: Fear Eats the Soul (Angst essen Seele auf) (1974),Alias Betty (Betty Fisher et autres histoires) (2001),Alice (1990),Alice (2009),Alice (Neco z Alenky) (1988),Alice Adams (1935),Alice Doesn't Live Here Anymore (1974),Alice Through the Looking Glass (2016),Alice in Wonderland (1933),Alice in Wonderland (1951),Alice in Wonderland (2010),Alien (1979),Alien Contamination (1980),Alien Nation (1988),Alien from L.A. (1988),Alien: Covenant (2017),Alien: Resurrection (1997),Aliens (1986),Alien³ (a.k.a. Alien 3) (1992),Alive (1993),All About Eve (1950),All About Lily Chou-Chou (Riri Shushu no subete) (2001),All About My Mother (Todo sobre mi madre) (1999),All About the Benjamins (2002),"All Dogs Christmas Carol, An (1998)",All Dogs Go to Heaven (1989),All Dogs Go to Heaven 2 (1996),All Good Things (2010),All Is Lost (2013),All Over the Guy (2001),All Quiet on the Western Front (1930),All Roads Lead to Rome (2016),All That Heaven Allows (1955),All That Jazz (1979),"All This, and Heaven Too (1940)",All Watched Over by Machines of Loving Grace (2011),All Yours (2016),All is Bright (2013),All of Me (1984),All or Nothing (2002),All the Boys Love Mandy Lane (2006),All the King's Men (1949),All the King's Men (2006),All the President's Men (1976),All the Pretty Horses (2000),All the Real Girls (2003),All the Right Moves (1983),All the Vermeers in New York (1990),All-Star Superman (2011),Allan Quatermain and the Lost City of Gold (1987),Allegro non troppo (1977),Alles Inklusive (2014),Alligator (1980),"Allnighter, The (1987)",Almost Famous (2000),Almost Heroes (1998),Almost an Angel (1990),Aloha (2015),Alone in the Dark (2005),Alone in the Dark II (2008),Along Came Polly (2004),Along Came a Spider (2001),Alpha (2018),Alpha Dog (2007),Alpha and Omega 3: The Great Wolf Games (2014),"Alphaville (Alphaville, une étrange aventure de Lemmy Caution) (1965)",Altered (2006),Altered States (1980),Alvarez Kelly (1966),Alvin and the Chipmunks (2007),Alvin and the Chipmunks: Chipwrecked (2011),Alvin and the Chipmunks: The Squeakquel (2009),Always (1989),Always Watching: A Marble Hornets Story (2015),Amadeus (1984),Amanda Knox (2016),Amarcord (1973),Amateur (1994),Amazing Grace (2006),Amazing Grace and Chuck (1987),"Amazing Panda Adventure, The (1995)","Amazing Spider-Man, The (2012)","Amazing Transparent Man, The (1960)",Amazon Women on the Moon (1987),"Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)",Amen. (2002),Amer (2009),America's Sweethearts (2001),"American Astronaut, The (2001)",American Beauty (1999),American Buffalo (1996),"American Carol, An (2008)",American Dreamz (2006),American Drug War: The Last White Hope (2007),American Fable (2017),American Flyers (1985),"American Friend, The (Amerikanische Freund, Der) (1977)",American Gangster (2007),American Gigolo (1980),American Graffiti (1973),American Grindhouse (2010),American Hardcore (2006),"American Haunting, An (2005)",American Heist (2015),American History X (1998),American Hustle (2013),American Made (2017),American Me (1992),American Movie (1999),American Ninja (1985),American Outlaws (2001),American Pie (1999),American Pie 2 (2001),American Pie Presents Beta House (American Pie 6: Beta House) (2007),American Pie Presents The Naked Mile (American Pie 5: The Naked Mile) (2006),American Pie Presents: Band Camp (American Pie 4: Band Camp) (2005),American Pie Presents: The Book of Love (American Pie 7: The Book of Love) (2009),American Pop (1981),"American President, The (1995)",American Psycho (2000),American Psycho II: All American Girl (2002),American Reunion (American Pie 4) (2012),American Sniper (2014),American Splendor (2003),"American Tail, An (1986)","American Tail: Fievel Goes West, An (1991)",American Ultra (2015),American Wedding (American Pie 3) (2003),"American Werewolf in London, An (1981)","American Werewolf in Paris, An (1997)","American in Paris, An (1951)","American, The (2010)",American: The Bill Hicks Story (2009),"Americanization of Emily, The (1964)",Americathon (1979),Amistad (1997),Amityville 1992: It's About Time (1992),Amityville 3-D (1983),"Amityville Curse, The (1990)","Amityville Horror, The (1979)","Amityville Horror, The (2005)",Amityville II: The Possession (1982),Amityville: A New Generation (1993),Amityville: Dollhouse (1996),Amores Perros (Love's a Bitch) (2000),Amos & Andrew (1993),Amy (2015),Amy's O (a.k.a. Amy's Orgasm) (2001),An Amazing Couple (2002),Anacleto: Agente secreto (2015),Anaconda (1997),Anaconda: The Offspring (2008),Anacondas: The Hunt for the Blood Orchid (2004),Analyze That (2002),Analyze This (1999),"Anarchist Cookbook, The (2002)",Anastasia (1956),Anastasia (1997),Anatomy of a Murder (1959),Anchorman 2: The Legend Continues (2013),Anchorman: The Legend of Ron Burgundy (2004),Anchors Aweigh (1945),And God Created Woman (Et Dieu... créa la femme) (1956),And Now... Ladies and Gentlemen... (2002),And So It Goes (2014),And Starring Pancho Villa as Himself (2003),And Then There Were None (1945),And Your Mother Too (Y tu mamá también) (2001),And the Band Played On (1993),And the Ship Sails On (E la nave va) (1983),"Andalusian Dog, An (Chien andalou, Un) (1929)",Andre (1994),Andrei Rublev (Andrey Rublyov) (1969),Andrew Dice Clay: Dice Rules (1991),Android (1982),"Andromeda Strain, The (1971)",Angel Baby (1995),Angel Eyes (2001),Angel Heart (1987),"Angel at My Table, An (1990)",Angel's Egg (Tenshi no tamago) (1985),Angel-A (2005),Angela's Ashes (1999),...,"Wages of Fear, The (Salaire de la peur, Le) (1953)",Wagons East (1994),Wait Until Dark (1967),Waiting for 'Superman' (2010),Waiting for Guffman (1996),Waiting to Exhale (1995),Waiting... (2005),Waitress (2007),"Wake Up, Ron Burgundy (2004)",Waking Life (2001),Waking Ned Devine (a.k.a. Waking Ned) (1998),Wal-Mart: The High Cost of Low Price (2005),"Walk Among the Tombstones, A (2014)",Walk Hard: The Dewey Cox Story (2007),"Walk in the Clouds, A (1995)",Walk of Shame (2014),"Walk on the Moon, A (1999)",Walk the Line (2005),"Walk to Remember, A (2002)","Walk, Don't Run (1966)",Walkabout (1971),Walker (1987),"Walker, The (2007)","Walking Dead, The (1995)",Walking Tall (2004),Walking and Talking (1996),Walking with Monsters (2005),Wall Street (1987),Wall Street: Money Never Sleeps (2010),Wallace & Gromit in The Curse of the Were-Rabbit (2005),Wallace & Gromit: A Close Shave (1995),Wallace & Gromit: The Best of Aardman Animation (1996),Wallace & Gromit: The Wrong Trousers (1993),Wallace and Gromit in 'A Matter of Loaf and Death' (2008),Walled In (2009),Waltz with Bashir (Vals im Bashir) (2008),Wanderlust (2012),Wanted (2008),War Dance (2007),War Dogs (2016),War Horse (2011),War Machine (2017),War Room (2015),"War Room, The (1993)","War Zone, The (1999)",War and Peace (1956),War and Peace (2016),War for the Planet of the Apes (2017),"War of the Roses, The (1989)",War of the Worlds (2005),"War of the Worlds, The (1953)","War, The (1994)",WarGames (1983),Warcraft (2016),Ward 13 (2003),Warm Bodies (2013),Warrior (2011),"Warrior's Way, The (2010)",Warriors of Heaven and Earth (Tian di ying xiong) (2003),"Warriors, The (1979)",Wasabi (2001),Washington Square (1997),"Wasp Woman, The (1959)",Watch Out for the Automobile (Beregis avtomobilya) (1966),Watch on the Rhine (1943),"Watch, The (2012)","Watcher in the Woods, The (1980)","Watcher, The (2000)",Watching the Detectives (2007),Watchmen (2009),Watchmen: Tales of the Black Freighter (2009),Water (2005),"Water Horse: Legend of the Deep, The (2007)",Water for Elephants (2011),"Waterboy, The (1998)","Waterdance, The (1992)",Watermark (2014),Watership Down (1978),Waterworld (1995),"Wave, The (Welle, Die) (2008)","Way Back, The (2010)","Way South, The (De weg naar het zuiden) (1981)","Way We Were, The (1973)","Way of the Dragon, The (a.k.a. Return of the Dragon) (Meng long guo jiang) (1972)","Way of the Gun, The (2000)","Way, Way Back, The (2013)",Waydowntown (2000),Wayne's World (1992),Wayne's World 2 (1993),We Are Marshall (2006),We Are What We Are (2013),We Bought a Zoo (2011),We Could Be King (2014),We Don't Live Here Anymore (2004),We Need to Talk About Kevin (2011),We Own the Night (2007),We Were Soldiers (2002),We're Back! A Dinosaur's Story (1993),We're No Angels (1955),We're No Angels (1989),We're the Millers (2013),"Weather Man, The (2005)","Weather Underground, The (2002)",Webmaster (1998),"Wedding Banquet, The (Xi yan) (1993)",Wedding Crashers (2005),"Wedding Date, The (2005)","Wedding Planner, The (2001)","Wedding Singer, The (1998)",Weekend (a.k.a. Le Week-end) (Week End) (1967),Weekend at Bernie's (1989),Weekend at Bernie's II (1993),Weird Science (1985),Weirdsville (2007),Welcome to Collinwood (2002),Welcome to Dongmakgol (2005),Welcome to Happiness (2015),Welcome to Me (2014),Welcome to Mooseport (2004),Welcome to Sarajevo (1997),Welcome to Woop-Woop (1997),Welcome to the Dollhouse (1995),Welcome to the Jungle (2013),Welcome to the Sticks (Bienvenue chez les Ch'tis) (2008),Wendigo (2001),Were the World Mine (2008),"Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A) (1994)",West Beirut (West Beyrouth) (1998),West Side Story (1961),Westworld (1973),Wet Hot American Summer (2001),Whale Rider (2002),What About Bob? (1991),What Dreams May Come (1998),What Ever Happened to Baby Jane? (1962),What Happened Was... (1994),"What Happened, Miss Simone? (2015)",What Happens in Vegas... (2008),What Have I Done to Deserve This? (¿Qué he hecho yo para merecer esto!!) (1984),What If (2013),What Lies Beneath (2000),What Love Is (2007),What Men Still Talk About (2011),What Men Talk About (2010),What Planet Are You From? (2000),What Time Is It There? (Ni neibian jidian) (2001),What We Do in the Shadows (2014),What Women Want (2000),What a Girl Wants (2003),What the #$*! Do We Know!? (a.k.a. What the Bleep Do We Know!?) (2004),What to Expect When You're Expecting (2012),What's Eating Gilbert Grape (1993),What's Love Got to Do with It? (1993),"What's New, Pussycat (1965)","What's Up, Doc? (1972)","What's Up, Tiger Lily? (1966)",What's Your Number? (2011),Whatever (1998),Whatever It Takes (2000),Whatever Works (2009),Wheels on Meals (Kuai can che) (1984),When Harry Met Sally... (1989),When Night Is Falling (1995),When We First Met (2018),When We Were Kings (1996),When Worlds Collide (1951),When You're Strange (2009),When a Man Loves a Woman (1994),When a Stranger Calls (1979),When a Stranger Calls (2006),When a Woman Ascends the Stairs (Onna ga kaidan wo agaru toki) (1960),When in Rome (2010),When the Cat's Away (Chacun cherche son chat) (1996),When the Levees Broke: A Requiem in Four Acts (2006),Where Eagles Dare (1968),Where the Buffalo Roam (1980),Where the Day Takes You (1992),Where the Heart Is (2000),Where the Money Is (2000),Where the Wild Things Are (2009),Where's Marlowe? (1998),While We're Young (2014),While You Were Fighting: A Thor Mockumentary (2016),While You Were Sleeping (1995),While the City Sleeps (1956),Whip It (2009),Whiplash (2013),Whiplash (2014),Whipped (2000),Whiskey Tango Foxtrot (2016),Whisper of the Heart (Mimi wo sumaseba) (1995),"Whistleblower, The (2010)","White Balloon, The (Badkonake sefid) (1995)",White Chicks (2004),White Christmas (1954),White Dog (1982),White Fang (1991),White Frog (2012),White Heat (1949),White House Down (2013),"White Hunter, Black H

In [6]:
def get_sim_ser_by_pearson(df_users, ser_target):
    corr_all = df_users.corrwith(ser_target, axis=1).dropna()
    return corr_all

In [7]:
def predict_scores(df_sim, ser_sim, ser_target):
    ret = {}
    df_sim_ave = df_sim.mean(axis=1)
    target_ave = ser_target.mean()
    for item1 in df_sim.columns:
        if item1 in ser_target.index: continue
        v1 = df_sim[item1]
        if v1.notnull().sum() < min_eval_users: continue
        v1 -= df_sim_ave
        v11 = v1[ v1.notnull() ]
        t11 = ser_sim[ v1.notnull() ]
        pred1 = target_ave + (v11 * t11).sum() / np.abs(t11).sum()
        ret[item1] = pred1
    
    ser_ret = pd.Series(ret)
    
    return ser_ret.sort_values(ascending=False)

In [8]:
def get_recomm_by_user_sim(df, target_dic):
    ser_target = pd.Series(target_dic)
    df_scores = df[ ser_target.index ]
    n_same_items = df_scores.notnull().sum(axis=1)
    df_common = df_scores[ n_same_items>=min_common_items ]
    
    ser_sim = get_sim_ser_by_pearson(df_common, ser_target)    
    df_sim = df.loc[ ser_sim.index ]
    recomm = predict_scores(df_sim, ser_sim, ser_target)

    return recomm

#### Do recommendation

In [9]:
recomm = get_recomm_by_user_sim(df,
                                {"Star Wars: The Last Jedi (2017)":5, 
                                 "Toy Story 2 (1999)":3, 
                                 "Toy Story 3 (2010)":5,
                                 "Beauty and the Beast (1991)":4
                                })
print('Number of items calculated:', len(recomm))
print('Recommendation:')
print(recomm.head(1))

Number of items calculated: 496
Recommendation:
Catwoman (2004)    6.41059
dtype: float64