In [1]:
import pandas as pd
import numpy as np

min_common_items = 4
min_eval_users = 3

pd.options.display.max_rows = 999 
pd.options.display.max_columns = 999

In [2]:
df=pd.read_csv('market.csv')

print(df.shape)
print(df.info())
display(df.head())

(69079, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69079 entries, 0 to 69078
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   レシートNo   69079 non-null  int64
 1   日        69079 non-null  int64
 2   時間       69079 non-null  int64
 3   顧客ID     69079 non-null  int64
 4   税抜価格     69079 non-null  int64
 5   税抜単価     69079 non-null  int64
 6   個数       69079 non-null  int64
 7   大カテゴリ番号  69079 non-null  int64
 8   大カテゴリ名   69079 non-null  object
 9   中カテゴリ番号  69079 non-null  int64
 10  中カテゴリ名   69079 non-null  object
 11  小カテゴリ番号  69079 non-null  int64
 12  小カテゴリ名   69079 non-null  object
dtypes: int64(10), object(3)
memory usage: 6.9+ MB
None

,レシートNo,日,時間,顧客ID,税抜価格,税抜単価,個数,大カテゴリ番号,大カテゴリ名,中カテゴリ番号,中カテゴリ名,小カテゴリ番号,小カテゴリ名
0,1,1,9,1518,50,10,5,11,農産,1113,野菜,111327,じゃが芋
1,1,1,9,1518,50,10,5,11,農産,1113,野菜,111363,玉葱
2,1,1,9,1518,90,90,1,11,農産,1113,野菜,111361,レタス
3,1,1,9,1518,185,185,1,11,農産,1113,野菜,111339,トマト
4,2,1,9,1532,85,85,1,11,農産,1113,野菜,111318,キャベツ

In [3]:
df_id = pd.read_csv('ID_data.csv')

print(df_id.shape)
print(df_id.info())
display(df_id.head())

(1000, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   顧客ID    1000 non-null   int64
 1   性別      1000 non-null   int64
 2   年代      1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB
None

   顧客ID  性別  年代
0  1001   2  70
1  1002   2  40
2  1003   2  20
3  1004   2  50
4  1005   2  40

In [4]:
df_merge=pd.merge(df,df_id,on='顧客ID', how='left')

In [5]:
display(df_merge.head())

,レシートNo,日,時間,顧客ID,税抜価格,税抜単価,個数,大カテゴリ番号,大カテゴリ名,中カテゴリ番号,中カテゴリ名,小カテゴリ番号,小カテゴリ名,性別,年代
0,1,1,9,1518,50,10,5,11,農産,1113,野菜,111327,じゃが芋,2,60
1,1,1,9,1518,50,10,5,11,農産,1113,野菜,111363,玉葱,2,60
2,1,1,9,1518,90,90,1,11,農産,1113,野菜,111361,レタス,2,60
3,1,1,9,1518,185,185,1,11,農産,1113,野菜,111339,トマト,2,60
4,2,1,9,1532,85,85,1,11,農産,1113,野菜,111318,キャベツ,1,40

In [6]:
df_agri = df_merge[df_merge['大カテゴリ名']=='農産']

In [7]:
df_agri_pivot = pd.pivot_table(df_agri, index='顧客ID', values="個数", columns="小カテゴリ名", aggfunc="sum")

In [8]:
display(df_agri_pivot.head())

小カテゴリ名,いちご,いちじく,えのき,おくら,かいわれ,かぶ,かぼちゃ,きのこ水煮,ごぼう,さくらんぼ,さつま芋,さやえんどう,ししとう,しめじ,しょうが,じゃが芋,すいか,その他きのこ,その他ハーブ,その他山菜,その他果物,その他輸入果物,その他野菜,そら豆,とうもろこし,なす,なめこ,にんにく,にんにくの芽,びわ,ぶどう,みかん,みつば,みょうが,もやし,らっきょう,りんご,れんこん,アスパラガス,アボカド,アメリカンチェリー,インゲン,エリンギ,オレンジ,カットキャベツ,カットフルーツ,カット妻物,カット野菜ミックス,カリフラワー,キウイフルーツ,キャベツ,キュウリ,クレソン,グレープフルーツ,ゴーヤ,スナップエンドウ,ズッキーニ,セロリ,チンゲン菜,トマト,ニラ,バジル,バナナ,パイナップル,パセリ,パプリカ,ピーマン,ブロッコリー,プラム,ベビーリーフ,ホウレン草,マッシュルーム,マンゴー,ミニトマト,メロン,モロヘイヤ,リーフレタス,ルッコラ,レタス,レモン,人参,冷凍果物,冷凍枝豆,冷凍野菜,冷凍野菜ミックス,地場野菜,大根,大葉,小松菜,山菜水煮,春菊,枝豆,桃,梅,椎茸,水菜,玉葱,白菜,筍水煮,舞茸,豆苗,豆類水煮,里芋,野菜水煮,野菜水煮ミックス,長芋,長葱,青葱
顧客ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,NaN,2.0,NaN,NaN,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,6.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1002,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,3.0,NaN,2.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,4.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,1.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
1004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN
1006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
def get_sim_ser_by_pearson(df_users, ser_target):
    corr_all = df_users.corrwith(ser_target, axis=1).dropna()
    return corr_all

In [10]:
def predict_scores(df_sim, ser_sim, ser_target):
    ret = {}
    df_sim_ave = df_sim.mean(axis=1)
    target_ave = ser_target.mean()
    for item1 in df_sim.columns:
        if item1 in ser_target.index: continue
        v1 = df_sim[item1]
        if v1.notnull().sum() < min_eval_users: continue
        v1 -= df_sim_ave
        v11 = v1[ v1.notnull() ]
        t11 = ser_sim[ v1.notnull() ]
        pred1 = target_ave + (v11 * t11).sum() / np.abs(t11).sum()
        ret[item1] = pred1
    
    ser_ret = pd.Series(ret)
    
    return ser_ret.sort_values(ascending=False)

In [11]:
def get_recomm_by_user_sim(df, target_dic):
    ser_target = pd.Series(target_dic)
    df_scores = df[ ser_target.index ]
    n_same_items = df_scores.notnull().sum(axis=1)
    df_common = df_scores[ n_same_items>=min_common_items ]
    
    ser_sim = get_sim_ser_by_pearson(df_common, ser_target)    
    df_sim = df.loc[ ser_sim.index ]
    recomm = predict_scores(df_sim, ser_sim, ser_target)

    return recomm

In [ ]:
recomm = get_recomm_by_user_sim(df_agri_pivot,
                                {'じゃが芋':1, 'レタス':1, 'キャベツ':3,
                                'ごぼう':4, 'かぼちゃ':4, 'かぶ':4})
print('Number of items calculated:', len(recomm))
print('Recommendation:')
print(recomm.head())

Number of items calculated: 67
Recommendation:
アボカド        5.291572
地場野菜        4.808358
その他野菜       4.495491
さやえんどう      4.370747
冷凍野菜ミックス    4.242757
dtype: float64

c:\Users\haseg\miniconda3\envs\ds2024\lib\site-packages\numpy\lib\function_base.py:2829: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
c:\Users\haseg\miniconda3\envs\ds2024\lib\site-packages\numpy\lib\function_base.py:2830: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]