In [1]:
import numpy as np
import pandas as pd
import pyfpgrowth

In [2]:
csv_in = 'market_ex.csv'

In [3]:
df = pd.read_csv(csv_in, sep=',', skiprows=0, header=None)
print(df.shape)
print(df.info())
display(df.head())

(6008, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6008 entries, 0 to 6007
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6008 non-null   object
 1   1       4592 non-null   object
 2   2       3491 non-null   object
 3   3       2674 non-null   object
 4   4       2029 non-null   object
 5   5       1497 non-null   object
 6   6       1106 non-null   object
 7   7       783 non-null    object
 8   8       524 non-null    object
 9   9       315 non-null    object
 10  10      202 non-null    object
 11  11      122 non-null    object
 12  12      71 non-null     object
 13  13      39 non-null     object
 14  14      20 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 938.9+ KB
None

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = df.replace(np.nan, '00nan')
display(df.head())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan
2,chutney,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan
3,turkey,avocado,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan
4,mineral water,milk,energy bar,whole wheat rice,green tea,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan,00nan

In [5]:
ser_items = pd.Series(df.values.flatten())
top_items = ser_items.value_counts()
print(top_items.head())

00nan            96667
mineral water     1430
eggs              1117
spaghetti         1017
french fries      1009
Name: count, dtype: int64

In [6]:
item1 = top_items.index[1]
item2 = top_items.index[2]
print(item1, item2)

mineral water eggs

In [7]:
df_bool1 = (df == item1)
display(df_bool1.head())
n_sc1 = df_bool1.values.sum()
print(n_sc1)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

1430

In [8]:
df_bool2 = (df == item2)
display(df_bool2.head())
n_sc2 = df_bool2.values.sum()
print(n_sc2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

1117

In [9]:
df_bool3 = ((df == item1) | (df == item2))
display(df_bool3.head())
count = df_bool3.values.sum(axis=1)
print(count[:20])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

[1 1 0 0 1 0 0 0 0 0 1 0 2 0 1 1 0 1 2 0]

In [10]:
n_either = np.sum(count>0)
print(n_either)

2236

In [11]:
n_both = np.sum(count==2)
print(n_both)

311

In [12]:
n_all = df.shape[0]

In [13]:
print('Jac(sc1 => sc2):',  n_both / n_either)

Jac(sc1 => sc2): 0.139087656529517

In [14]:
print('Supp(sc1 => sc2):', n_both / n_all)

Supp(sc1 => sc2): 0.05176431424766977

In [15]:
print('Conf(sc1 => sc2):', n_both / n_sc1)  
print('Conf(sc2 => sc1):', n_both / n_sc2)

Conf(sc1 => sc2): 0.21748251748251748
Conf(sc2 => sc1): 0.2784243509400179

In [16]:
a = n_both / n_sc1
b = n_sc2 / n_all
print('Lift(sc1 => sc2):', a/b)

Lift(sc1 => sc2): 1.1697716786347045