### Sample script for user-based collaborative filtering

#### Import libraries

In [1]:
import numpy as np
import pandas as pd

#### Parameters

In [2]:
csv_in = 'df_13_assignment.csv'
# min number of common items between target user and users in DB
min_common_items = 2
# min number of users who evaluated an item to be recommended
min_eval_users = 2

# To show more rows and columns
pd.options.display.max_rows = 999 
pd.options.display.max_columns = 999

#### Read CSV file

In [3]:
df = pd.read_csv(csv_in, sep=' ', skiprows=0, header=0)
print(df.shape)
display(df.info())
display(df.head())

(100, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1 to 100
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       100 non-null    int64
 1   b       100 non-null    int64
 2   c       100 non-null    int64
 3   d       100 non-null    int64
 4   e       100 non-null    int64
 5   f       100 non-null    int64
 6   g       100 non-null    int64
 7   h       100 non-null    int64
 8   i       100 non-null    int64
 9   j       100 non-null    int64
 10  k       100 non-null    int64
 11  l       100 non-null    int64
 12  m       100 non-null    int64
 13  n       100 non-null    int64
 14  o       100 non-null    int64
 15  p       100 non-null    int64
dtypes: int64(16)
memory usage: 13.3 KB

None

   a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p
1  0  0  0  1  0  0  0  0  4  0  1  4  0  0  5  0
2  0  0  0  0  0  2  0  0  0  0  0  0  3  0  2  0
3  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0
4  3  3  0  0  5  5  0  1  2  2  0  2  0  0  0  1
5  0  0  0  0  3  0  0  0  3  5  0  5  0  4  0  0

#### Replace -1 into NaN (for not to be used during calculation)

In [4]:
df = df.replace(0, np.nan)
display(df.head())

,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p
1,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,4.0,NaN,1.0,4.0,NaN,NaN,5.0,NaN
2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,NaN
3,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,3.0,NaN,NaN,5.0,5.0,NaN,1.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,1.0
5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0,5.0,NaN,5.0,NaN,4.0,NaN,NaN

#### Return Series of similiarity of users  
by using Pearson correlation coefficient (-1 .. 1).

In [5]:
def get_sim_ser_by_pearson(df_users, ser_target):
    corr_all = df_users.corrwith(ser_target, axis=1).dropna()
    return corr_all